trigger: none
pr: none

resources:
  repositories:
    - repository: recommended_practices
      type: github
      name: endjin/Endjin.RecommendedPractices.AzureDevopsPipelines.GitHub
      endpoint: ${{ Endjin_Service_Connection_GitHub }}

jobs:
- template: templates/tag.for.release.yml@recommended_practices
  parameters:
    vmImage: 'windows-latest'
    service_connection_github: $(Endjin_Service_Connection_GitHub)